fix setuptools version error
Traceback (most recent call last):
  File "/usr/bin/jenkins-jobs", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.6/site-packages/jenkins_jobs/cmd.py", line 121, in main
    parser = create_parser()
  File "/usr/lib/python2.6/site-packages/jenkins_jobs/cmd.py", line 107, in create_parser
    version=version(),
  File "/usr/lib/python2.6/site-packages/jenkins_jobs/cmd.py", line 240, in version
    jenkins_jobs.version.version_info.version_string()
  File "/usr/lib/python2.6/site-packages/pbr/version.py", line 78, in version_string
    for part in self.release_string().split('.'):
  File "/usr/lib/python2.6/site-packages/pbr/version.py", line 70, in release_string
    self.release = self._get_version_from_pkg_resources()
  File "/usr/lib/python2.6/site-packages/pbr/version.py", line 62, in _get_version_from_pkg_resources
    return packaging.get_version(self.package)
  File "/usr/lib/python2.6/site-packages/pbr/packaging.py", line 554, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?

Change-Id: I9521fb2a00ae2b88f0d652014160b56eb4684001