Update patch set 1
Patch Set 1:

This seems not enough for our usecase.

We have the following job definition (shortened):

  - job:
      name: trigger-upstream-nightly
      wrappers:
          - build-name:
              name: '#${BUILD_NUMBER} ${ENV,var="BUILD_LABEL"}'


Which raises the following error:
jenkins_jobs.errors.JenkinsJobsException: BUILD_NUMBER parameter missing to format #${BUILD_NUMBER} ${ENV,var="BUILD_LABEL"}

Patch-set: 1