fix delete job command
change I126751e3 introduced recursive file definition feature however it broke
the ability to delete jobs.  This changes fixes it.

This was the error when trying to delete a job:

(py27)~/jenkins-job-builder$ jenkins-jobs --conf jenkins_jobs.ini delete myjob
INFO:root:Deleting jobs in [myjob]
Traceback (most recent call last):
  File "/jenkins-job-builder/.tox/py27/bin/jenkins-jobs", line 10, in <module>
    sys.exit(main())
  File "/jenkins-job-builder/jenkins_jobs/cmd.py", line 122, in main
    execute(options, config)
  File "/jenkins-job-builder/jenkins_jobs/cmd.py", line 207, in execute
    builder.delete_job(job, options.path)
  File "/jenkins-job-builder/jenkins_jobs/builder.py", line 611, in delete_job
    self.load_files(fn)
  File "/jenkins-job-builder/jenkins_jobs/builder.py", line 576, in load_files
    if os.path.isdir(path):
  File "/jenkins-job-builder/.tox/py27/lib/python2.7/genericpath.py", line 41,
    in isdir st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found

Change-Id: Ib87fa497d80ba33470c049f875658a3878afb664