Update patch set 1
Patch Set 1:

Just tried running this patch and found that it causes authentication error when I try to upload a job. I think it's probably not using the credentials from my jenkins_jobs.ini correctly.

jenkins.JenkinsException: Error in request. Possibly authentication failed [403]: Forbidden

Patch-set: 1