make maven and freestyle job creation consistent
Creating a freestyle job without any builder will generate a basic xml
configuration for the job.  Creating a maven job without any builders
will throw an error.  I think the behavior should be consistent in both
cases.  Creating the maven job should work also generate a basic xml
configuration for the job. This patch just makes it so that the maven
job and freestyle job creation work the same.

This is the error:
Traceback (most recent call last):
  File "/home/khaido/workspace/jenkins-job-builder/.tox/py27/bin/jenkins-jobs", line 9, in <module>
    load_entry_point('jenkins-job-builder==0.6.0.14.g04be0f4', 'console_scripts', 'jenkins-jobs')()
  File "/home/khaido/workspace/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/jenkins_jobs/cmd.py", line 123, in main
    output_dir=options.output_dir)
  File "/home/khaido/workspace/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 522, in update_job
    self.parser.generateXML(names)
  File "/home/khaido/workspace/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 142, in generateXML
    self.getXMLForJob(job)
  File "/home/khaido/workspace/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 249, in getXMLForJob
    self.gen_xml(xml, data)
  File "/home/khaido/workspace/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 257, in gen_xml
    module.gen_xml(self, xml, data)
  File "/home/khaido/workspace/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/jenkins_jobs/modules/general.py", line 59, in gen_xml
    XML.SubElement(xml, 'actions')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 530, in SubElement
    element = parent.makeelement(tag, attrib)
AttributeError: 'NoneType' object has no attribute 'makeelement'

Change-Id: If7b749dae7631e8714a9416dfbd82d2443c0302c