Update patch set 1
Patch Set 1:

And removing the .egg file doesn't help as it simply gets redownloaded because of setup_requires.

    $ rm -rf pbr-0.8.0-py2.7.egg
    $python setup.py install
    ...
    Installed /Users/marca/dev/git-repos/jenkins-job-builder/pbr-0.8.0-py2.7.egg
    ...
    Requirement already satisfied (use --upgrade to upgrade): pbr>=0.5.21,<1.0 in ./pbr-0.8.0-py2.7.egg

    $ pip freeze | grep pbr

    $ python -c 'import jenkins_jobs.version'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "jenkins_jobs/version.py", line 18, in <module>
        from pbr.version import VersionInfo
    ImportError: No module named pbr.version

Patch-set: 1