Update patch set 4
Patch Set 4:

I was able to repo with py34, but not py27.

Traceback (most recent call last):
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/bin/jenkins-jobs", line 10, in <module>
    sys.exit(main())
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/jenkins_jobs/cmd.py", line 191, in main
    execute(options, config)
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/jenkins_jobs/cmd.py", line 372, in execute
    n_workers=options.n_workers)
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/jenkins_jobs/builder.py", line 420, in update_jobs
    self.cache.save()
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/jenkins_jobs/builder.py", line 108, in save
    self._yaml.dump(self.data, utils.wrap_stream(tfile))
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/__init__.py", line 188, in dump_all
    dumper.represent(data)
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/representer.py", line 27, in represent
    self.serialize(node)
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/serializer.py", line 54, in serialize
    self.serialize_node(node, None, None)
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/serializer.py", line 107, in serialize_node
    self.serialize_node(key, node, None)
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/serializer.py", line 90, in serialize_node
    style=node.style))
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/emitter.py", line 115, in emit
    self.state()
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/emitter.py", line 228, in expect_document_root
    self.expect_node(root=True)
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/emitter.py", line 254, in expect_node
    self.expect_flow_mapping()
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/emitter.py", line 311, in expect_flow_mapping
    self.write_indicator('{', True, whitespace=True)
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/site-packages/yaml/emitter.py", line 811, in write_indicator
    self.stream.write(data)
  File "/Users/zaro0508/PyCharmProjects/jenkins-job-builder/.tox/py34/lib/python3.4/tempfile.py", line 399, in func_wrapper
    return func(*args, **kwargs)
TypeError: 'str' does not support the buffer interface
ERROR:jenkins_jobs.builder:Failed to write to cache file '/Users/zaro0508/.cache/jenkins_jobs/cache-host-jobs-http___dockerhost_8080.yml' on exit: 'str' does not support the buffer interface

Patch-set: 4