Update patch set 1
Patch Set 1:

They are similar but don't achieve the same. I have pick my example files and ran them against https://review.openstack.org/#/c/85336/ and that fails

 JenkinsJobsException: arch parameter missing to format echo Build arch {arch}.
 Given: {'': '', 'jobs': ['build-{arch}', {'build-{arch}': {'arch': 'amd64'}}], 'name': 'project-name'}

My patch acts earlier in getXMLForTemplateJob() and apply the default to the job template parameters.  The other does the formatting first then apply defaults to the result.  With my example the expansion is missing some parameter.

Patch-set: 1