Update patch set 2
Patch Set 2: Code-Review-1

Whoops...I tried breaking a test locally by simply modifying the expected XML output for a test:

    diff --git a/tests/builders/fixtures/copy-artifact002.xml b/tests/builders/fixtures/copy-artifact002.xml
    index 5b1e9a5..e34f0ce 100644
    --- a/tests/builders/fixtures/copy-artifact002.xml
    +++ b/tests/builders/fixtures/copy-artifact002.xml
    @@ -3,7 +3,7 @@
       <builders>
         <hudson.plugins.copyartifact.CopyArtifact>
           <project>foo</project>
    -      <filter>*.txt</filter>
    +      <filter>.txt</filter>
           <target>/home/foo</target>
           <flatten>true</flatten>
           <optional>true</optional>

This led to:

    py27 develop-inst-nodeps: /home/wayne/projects/jenkins-job-builder
    py27 installed: coverage==4.0,discover==0.4.0,docutils==0.12,extras==0.0.3,fixtures==1.3.1,flake8==2.2.4,funcsigs==0.4,hacking==0.10.2,## !! Could not determine repository location,jenkins-job-builder==1.3.1.dev23,Jinja2==2.8,linecache2==1.0.0,MarkupSafe==0.23,mccabe==0.2.1,mock==1.3.0,multi-key-dict==2.0.3,ordereddict==1.1,pbr==1.8.0,pep8==1.5.7,pyflakes==0.8.1,Pygments==2.0.2,python-jenkins==0.4.10,python-mimeparse==0.1.4,python-subunit==1.1.0,PyYAML==3.11,setuptools-git==1.1,six==1.9.0,Sphinx==1.1.3,sphinxcontrib-programoutput==0.8,testrepository==0.0.20,testscenarios==0.5.0,testtools==1.8.0,traceback2==1.4.0,unittest2==1.1.0,wheel==0.24.0
    py27 runtests: PYTHONHASHSEED='0'
    py27 runtests: commands[0] | python setup.py testr --slowest --testr-args=
    running testr
    Traceback (most recent call last):
      File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/lib/python2.7/site-packages/subunit/run.py", line 149, in <module>
        main()
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/lib/python2.7/site-packages/subunit/run.py", line 145, in main
        stdout=stdout, exit=False)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testtools/run.py", line 187, in __init__
        self.runTests()
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testtools/run.py", line 221, in runTests
        self.result = testRunner.run(self.test)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/lib/python2.7/site-packages/subunit/run.py", line 70, in run
        test(result)
      File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
        return self.run(*args, **kwds)
      File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
        test(result)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/unittest2/suite.py", line 87, in __call__
        return self.run(*args, **kwds)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/unittest2/suite.py", line 126, in run
        test(result)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/unittest2/suite.py", line 87, in __call__
        return self.run(*args, **kwds)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/unittest2/suite.py", line 126, in run
        test(result)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/unittest2/suite.py", line 87, in __call__
        return self.run(*args, **kwds)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/unittest2/suite.py", line 126, in run
        test(result)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/unittest2/case.py", line 673, in __call__
        return self.run(*args, **kwds)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testscenarios/testcase.py", line 62, in run
        test.run(result)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testscenarios/testcase.py", line 65, in run
        return super(WithScenarios, self).run(result)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py", line 606, in run
        return run_test.run(result)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testtools/runtest.py", line 80, in run
        return self._run_one(actual_result)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testtools/runtest.py", line 94, in _run_one
        return self._run_prepared_result(ExtendedToOriginalDecorator(result))
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testtools/runtest.py", line 108, in _run_prepared_result
        self._run_core()
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testtools/runtest.py", line 144, in _run_core
        self.case._run_test_method, self.result):
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testtools/runtest.py", line 193, in _run_user
        return self._got_user_exception(sys.exc_info())
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testtools/runtest.py", line 213, in _got_user_exception
        self.case.onException(exc_info, tb_label=tb_label)
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/testtools/testcase.py", line 558, in onException
        handler(exc_info)
      File "tests/base.py", line 113, in _add_logging_detail
        self.logger_fixture.getDetails()["pythonlogging:''"])
      File "/home/wayne/projects/jenkins-job-builder/.tox/py27/local/lib/python2.7/site-packages/fixtures/fixture.py", line 170, in getDetails
        result = dict(self._details)
    TypeError: 'NoneType' object is not iterable
    INFO:jenkins_jobs.builder:Cache saved
    jenkins_jobs/xml_config.py:74: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
      for child in node.getchildren():
    jenkins_jobs/xml_config.py:74: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
      for child in node.getchildren():
    running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} OS_LOG_CAPTURE=${OS_LOG_CAPTURE:-1} ${PYTHON:-python} -m subunit.run discover -t ./ tests --list
    running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} OS_LOG_CAPTURE=${OS_LOG_CAPTURE:-1} ${PYTHON:-python} -m subunit.run discover -t ./ tests  --load-list /tmp/tmpMduf5o
    running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} OS_LOG_CAPTURE=${OS_LOG_CAPTURE:-1} ${PYTHON:-python} -m subunit.run discover -t ./ tests  --load-list /tmp/tmpHhscd1
    running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} OS_LOG_CAPTURE=${OS_LOG_CAPTURE:-1} ${PYTHON:-python} -m subunit.run discover -t ./ tests  --load-list /tmp/tmpJpgeNO
    running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} OS_LOG_CAPTURE=${OS_LOG_CAPTURE:-1} ${PYTHON:-python} -m subunit.run discover -t ./ tests  --load-list /tmp/tmp5FUuRi
    ======================================================================
    FAIL: process-returncode
    tags: worker-0
    ----------------------------------------------------------------------
    returncode 1
    Ran 351 (+3) tests in 3.416s (-0.515s)
    FAILED (id=13, failures=1)
    error: testr failed (1)
    ERROR: InvocationError: '/home/wayne/projects/jenkins-job-builder/.tox/py27/bin/python setup.py testr --slowest --testr-args='
    ___________________________________ summary ____________________________________
    ERROR:   py27: commands failed

as opposed to the following without the above change:

    py27 develop-inst-nodeps: /home/wayne/projects/jenkins-job-builder
    py27 installed: coverage==4.0,discover==0.4.0,docutils==0.12,extras==0.0.3,fixtures==1.3.1,flake8==2.2.4,funcsigs==0.4,hacking==0.10.2,## !! Could not determine repository location,jenkins-job-builder==1.3.1.dev23,Jinja2==2.8,linecache2==1.0.0,MarkupSafe==0.23,mccabe==0.2.1,mock==1.3.0,multi-key-dict==2.0.3,ordereddict==1.1,pbr==1.8.0,pep8==1.5.7,pyflakes==0.8.1,Pygments==2.0.2,python-jenkins==0.4.10,python-mimeparse==0.1.4,python-subunit==1.1.0,PyYAML==3.11,setuptools-git==1.1,six==1.9.0,Sphinx==1.1.3,sphinxcontrib-programoutput==0.8,testrepository==0.0.20,testscenarios==0.5.0,testtools==1.8.0,traceback2==1.4.0,unittest2==1.1.0,wheel==0.24.0
    py27 runtests: PYTHONHASHSEED='0'
    py27 runtests: commands[0] | python setup.py testr --slowest --testr-args=
    running testr
    INFO:jenkins_jobs.builder:Cache saved
    INFO:jenkins_jobs.builder:Cache saved
    jenkins_jobs/xml_config.py:74: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
      for child in node.getchildren():
    jenkins_jobs/xml_config.py:74: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
      for child in node.getchildren():
    jenkins_jobs/xml_config.py:74: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
      for child in node.getchildren():
    running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} OS_LOG_CAPTURE=${OS_LOG_CAPTURE:-1} ${PYTHON:-python} -m subunit.run discover -t ./ tests --list
    running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} OS_LOG_CAPTURE=${OS_LOG_CAPTURE:-1} ${PYTHON:-python} -m subunit.run discover -t ./ tests  --load-list /tmp/tmpz4W2rn
    running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} OS_LOG_CAPTURE=${OS_LOG_CAPTURE:-1} ${PYTHON:-python} -m subunit.run discover -t ./ tests  --load-list /tmp/tmpf0YZ8r
    running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} OS_LOG_CAPTURE=${OS_LOG_CAPTURE:-1} ${PYTHON:-python} -m subunit.run discover -t ./ tests  --load-list /tmp/tmpwukZUA
    running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} OS_LOG_CAPTURE=${OS_LOG_CAPTURE:-1} ${PYTHON:-python} -m subunit.run discover -t ./ tests  --load-list /tmp/tmpF9cVPH
    Ran 552 (+201) tests in 5.045s (+1.631s)
    PASSED (id=14)
    Slowest Tests
    Test id                                                                                                                             Runtime (s)
    ----------------------------------------------------------------------------------------------------------------------------------  -----------
    tests.jsonparser.test_jsonparser.TestCaseModuleJsonParser.test_yaml_snippet(tests/jsonparser/fixtures/complete001.json)             0.126
    tests.duplicates.test_duplicates.TestCaseModuleDuplicates.test_yaml_snippet(tests/duplicates/fixtures/allow_duplicates001.yaml)     0.110
    tests.cmd.subcommands.test_test.TestJenkinsGetPluginInfoError.test_skip_plugin_retrieval_if_disabled                                0.107
    tests.cmd.subcommands.test_test.TestJenkinsGetPluginInfoError.test_skip_plugin_retrieval_if_no_config_provided                      0.097
    tests.cmd.subcommands.test_delete.DeleteTests.test_delete_using_glob_params                                                         0.095
    tests.duplicates.test_duplicates.TestCaseModuleDuplicates.test_yaml_snippet(tests/duplicates/fixtures/exception_job_group001.yaml)  0.092
    tests.duplicates.test_duplicates.TestCaseModuleDuplicates.test_yaml_snippet(tests/duplicates/fixtures/exception_templates001.yaml)  0.084
    tests.duplicates.test_duplicates.TestCaseModuleDuplicates.test_yaml_snippet(tests/duplicates/fixtures/allow_templates001.yaml)      0.082
    tests.duplicates.test_duplicates.TestCaseModuleDuplicates.test_yaml_snippet(tests/duplicates/fixtures/duplicates002.yaml)           0.081
    tests.duplicates.test_duplicates.TestCaseModuleDuplicates.test_yaml_snippet(tests/duplicates/fixtures/allow_projects001.yaml)       0.078
    ___________________________________ summary ____________________________________
      py27: commands succeeded
      congratulations :)

Patch-set: 2
Reviewer: Gerrit User 13487 <13487@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Code-Review=-1