Update patch set 3
Patch Set 3:

> I am against this patch because is using a high maintenance design.
 > Mainly if we will want to add something else than jobs or views we
 > will endup with a parameter nightmare.
 > 
 > Please find a better design that is more flexible. The default
 > is to update "all". Maybe we can use soemthing like `--limit
 > jobs,views,...`, or even using --tags instead of limit and having
 > the jobs and views tags with implicit meanings (inspired from
 > ansible).

We have actual users using these parameters already today so I think it will be difficult to break them unless we deprecate in 2.0 and release a 3.0 (following semver). In any case I think this code will make it easier to maintain:

 import argparse
 parser = argparse.ArgumentParser()
 parser.add_argument('--jobs-only', dest='update', 
 action='append_const', const='jobs')
 parser.add_argument('--views-only', dest='update', 
 action='append_const', const='views')
 args = parser.parse_args()
  
 if args.update:
     if len(args.update) == 1:
         update = args.update[0]
     else:
         raise Exception('ERROR: Cannot use more than 1 --(jobs|views)-only command.')
 else:
     update = 'all'
  
 print(update)
  
  
 ---- snip ----
 
 $ python /tmp/script.py
 all
 
 $ python /tmp/script.py --jobs-only
 jobs
  
 $ python /tmp/script.py --views-only
 views
  
 $ python /tmp/script.py --jobs-only --views-only
 Traceback (most recent call last):
 File "/tmp/script.py", line 11, in <module>
 raise Exception('ERROR: Cannot use more than 1 --(jobs|views)- only command.')
 Exception: ERROR: Cannot use more than 1 --(jobs|views)-only 
 command.

With this method we only need to add the parameter and not have to mess with the logic every time.

Patch-set: 3
Label: Verified=0