Fix: add support for fips-enabled systems using Python3.6 or greater.
FIPS restricts usage of md5 and requires the flag 'usedforsecurity' to be
set False in order to avoid error:

ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS

Change-Id: I99a4ad0bf78bbeb898fb9dcfc79c03a14d596235