Update patch set 3
Patch Set 3: No score

The change mentioned by James got merged, but OpenStack configuration still has some issue apparently:

 jenkins_jobs.errors.JenkinsJobsException: Unknown entry point or macro 'console-log-post' for component type: 'publisher'.

Patch-set: 3