Update patch set 4
Patch Set 4:

This patch broke JJB for me. I'm using Python 3.5 and I'm getting this error every time I push jobs now:

TypeError: a bytes-like object is required, not 'str'
ERROR:jenkins_jobs.builder:Failed to write to cache file '/home/user/.cache/jenkins_jobs/cache-host-jobs-https___jenkins_opendaylight_org_releng.yml' on exit: a bytes-like object is required, not 'str'

Patch-set: 4