Update patch set 1
Patch Set 1:

Antoine, your `install_requires` change doesn't work for me. It doesn't cause pbr to get installed in my virtualenv so things still crap out if they need pbr and can't find it.

    $ pip install -e .
    ...
    Requirement already satisfied (use --upgrade to upgrade): pbr>=0.5.21,<1.0 in ./pbr-0.8.0-py2.7.egg (from jenkins-job-builder==0.7.0.95.gff70493)
    ...

    $ pip freeze | grep pbr

    $ python -c 'import jenkins_jobs.version'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "jenkins_jobs/version.py", line 18, in <module>
        from pbr.version import VersionInfo
    ImportError: No module named pbr.version

I don't how to handle this, if we are going to require pbr at runtime as https://review.openstack.org/#/c/90658/ will do.

Patch-set: 1
Reviewer: Gerrit User 11011 <11011@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Verified=0