Update patch set 1
Patch Set 1:

> > Uploaded patch set 1.
 > 
 > Why was this reverted?

As mentioned in the original patch. I think we need to track down what the regression caused by this patch is before trying again as it seems to cause a failure for one of our projects.

This patch seems to break us with this error:

Traceback (most recent call last):
  File "/tmp/tmp.riVVygKQhh/bin/jenkins-jobs", line 11, in <module>
    sys.exit(main())
  File "/tmp/tmp.riVVygKQhh/lib/python2.7/site-packages/jenkins_jobs/cli/entry.py", line 158, in main
    jjb.execute()
  File "/tmp/tmp.riVVygKQhh/lib/python2.7/site-packages/jenkins_jobs/cli/entry.py", line 139, in execute
    ext.obj.execute(self.options, self.jjb_config)
  File "/tmp/tmp.riVVygKQhh/lib/python2.7/site-packages/jenkins_jobs/cli/subcommand/test.py", line 58, in execute
    config_xml=options.config_xml)
  File "/tmp/tmp.riVVygKQhh/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 301, in update_jobs
    f.write(job.output().decode('utf-8'))
  File "/tmp/tmp.riVVygKQhh/lib/python2.7/site-packages/jenkins_jobs/xml_config.py", line 62, in output
    out = minidom.parseString(XML.tostring(self.xml, encoding='UTF-8'))
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1075, in _escape_cdata
    _raise_serialization_error(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1052, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize 1 (type int)
DEBUG:jenkins_jobs.cache:Cache written out to '/home/jenkins/.cache/jenkins_jobs/cache-host-jobs-https___jenkins_opendaylight_org_releng.yml'
Build step 'Execute shell' marked build as failure

Patch-set: 1