Update patch set 5
Patch Set 5: Code-Review-1

That might help with some installation that actually don't need duplicate. I would just throw a warning and keep proceeding as we were previously but that is a matter of taste.

The Openstack JJB config does not pass (see result of jenkins-job-builder-compare-xml ).  I believe that needs to be fixed before pushing this change.  The error:

 ERROR:jenkins_jobs.builder:Duplicate entry found: 'gate-{name}-build' is already defined
 <snip stacktrace>
 jenkins_jobs.errors.JenkinsJobsException: Duplicate entry found: 'gate-{name}-build' is already defined

( http://logs.openstack.org/34/56734/5/check/jenkins-job-builder-compare-xml/25825cc/console.html.gz )

This might need to be caught and a user friendly message displayed instead of the stacktrace.


Overall, being stricter sounds like a good idea to me.

Patch-set: 5
Label: Code-Review=-1