fix for python 3, decode job output
Change Ie952617a34c0719e forced utf-8 format but forgot to decode the
xml when passing to update_job. This broke jjb for python 3:

 File "/Users/khaido/PycharmProjects/jenkins-job-builder
     /jenkins_jobs/builder.py", line
 134, in update_job
    self.jenkins.create_job(job_name, xml)

 File "/Users/khaido/PycharmProjects/jenkins-job-builder/.tox
      /py34/lib/python3.4/site-packages/jenkins/__init__.py",
 line 852, in create_job
      config_xml.encode('utf-8'), DEFAULT_HEADERS))
  AttributeError: 'function' object has no attribute 'encode'

Change-Id: Iceda46214bf4709ccd8141ef654cf3ec81e8af06