Update patch set 12
Patch Set 12:

It would be nice if we could make argv required for main but I don't think we can because main is invoked as a setuptools entry point when the `jenkins-jobs` command is run from the shell:

$ grep -Hn main setup.cfg
setup.cfg:30:    jenkins-jobs=jenkins_jobs.cmd:main

From http://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation:

> The functions you specify are called with no arguments

Thus, if I make that change, this results:

    $ jenkins-jobs test
    Traceback (most recent call last):
      File "/Users/marca/python/virtualenvs/jenkins-job-builder/bin/jenkins-jobs", line 10, in <module>
        sys.exit(main())
    TypeError: main() takes exactly 1 argument (0 given)

This guy has some code that looks very similar to mine:

https://www.artima.com/weblogs/viewpost.jsp?thread=4829

:-)

Patch-set: 12
Reviewer: Gerrit User 11011 <11011@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Verified=0