Update patch set 9
Patch Set 9: Code-Review+1

Tested this patch set and now this works for me:
jenkins-jobs update --delete-old /etc/jenkins_jobs/config

Previously I had this error:

err: /Stage[main]/Jenkins::Job_builder/Exec[jenkins_jobs_update]: Failed to call refresh: jenkins-jobs update --delete-old /etc/jenkins_jobs/config returned 1 instead of one of [0] at /root/system-config/modules/jenkins/manifests/job_builder.pp:67
notice: Finished catalog run in 42.41 seconds
2d [stack@ramy-stack1:~]? 53s $ sudo  jenkins-jobs update --delete-old /etc/jenkins_jobs/config
Traceback (most recent call last):
  File "/usr/local/bin/jenkins-jobs", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/cmd.py", line 121, in main
    parser = create_parser()
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/cmd.py", line 107, in create_parser
    version=version(),
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/cmd.py", line 241, in version
    jenkins_jobs.version.version_info.version_string()
  File "/usr/local/lib/python2.7/dist-packages/pbr/version.py", line 78, in version_string
    for part in self.release_string().split('.'):
  File "/usr/local/lib/python2.7/dist-packages/pbr/version.py", line 70, in release_string
    self.release = self._get_version_from_pkg_resources()
  File "/usr/local/lib/python2.7/dist-packages/pbr/version.py", line 62, in _get_version_from_pkg_resources
    return packaging.get_version(self.package)
  File "/usr/local/lib/python2.7/dist-packages/pbr/packaging.py", line 871, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?

Patch-set: 9
Reviewer: Gerrit User 9624 <9624@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Code-Review=+1